version: '3'
services:
  db:
    image: postgres:10.8-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=
    volumes:
      - psql:/var/lib/postgresql/10.8/data
    ports:
      - '5432'
    networks:
      - 'application-network'
  web:
    tty: true
    stdin_open: true
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/weather-challenge
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - application-network

networks:
  application-network:
    driver: bridge
volumes:
  psql:

