default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: db
  username: postgres
  password:

test:
  <<: *default
  database: WEATHER_test
development:
  <<: *default
  database: WEATHER_development
production:
  <<: *default
  database: WEATHER_production
